---
# Ensure Node.js is installed
- name: Ensure Node.js is installed
  apt:
    name: nodejs
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'

# Ensure npm is installed
- name: Ensure npm is installed
  apt:
    name: npm
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'

# Install pm2 globally
- name: Install pm2 globally
  npm:
    name: pm2
    global: yes

# Enable pm2 to start on boot for www-data
- name: Enable pm2 to start on boot for www-data
  shell: |
    sudo env PATH=$PATH:/opt/bitnami/node/bin pm2 startup systemd -u www-data --hp /var/www
  become: true
  args:
    executable: /bin/bash

# Save pm2 process list for www-data
- name: Save pm2 process list for www-data
  shell: pm2 save
  become: true
  become_user: www-data
  args:
    executable: /bin/bash


# Create /var/www/blue and /var/www/green directories
- name: Create directories for blue-green deployment
  file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop:
    - blue
    - green

# Check if deployment_info.txt exists, if not create it with default value: blue
- name: Check if deployment_info.txt exists
  stat:
    path: /var/www/deployment_info.txt
  register: deployment_info

- name: Create deployment_info.txt with default value if it does not exist
  copy:
    dest: /var/www/deployment_info.txt
    owner: www-data
    group: www-data
    mode: '0644'
    content: "blue"
  when: not deployment_info.stat.exists

# Check if deployment_history.txt exists
- name: Check if deployment_history.txt exists
  stat:
    path: /var/www/deployment_history.txt
  register: deployment_history

- name: Create deployment_history.txt if it does not exist
  copy:
    dest: /var/www/deployment_history.txt
    owner: www-data
    group: www-data
    mode: '0644'
    content: ""
  when: not deployment_history.stat.exists
