AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create S3 buckets for 0dev.io and www.0dev.io with static hosting

Parameters:
  DomainName:
    Description: The apex domain name (e.g., 0dev.io)
    Type: String
    Default: "0dev.io"

Resources:
  RootDomainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain

  WwwDomainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "www.${DomainName}"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain

  RootDomainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootDomainBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudflareIPs"
            Effect: Deny
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${DomainName}/*"
            Condition:
              NotIpAddress:
                aws:SourceIp:
                  - 173.245.48.0/20
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 141.101.64.0/18
                  - 108.162.192.0/18
                  - 190.93.240.0/20
                  - 188.114.96.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17
                  - 162.158.0.0/15
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 172.64.0.0/13
                  - 131.0.72.0/22
                  - 2400:cb00::/32
                  - 2606:4700::/32
                  - 2803:f800::/32
                  - 2405:b500::/32
                  - 2405:8100::/32
                  - 2a06:98c0::/29
                  - 2c0f:f248::/32

  WwwDomainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WwwDomainBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudflareIPs"
            Effect: Deny
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::www.${DomainName}/*"
            Condition:
              NotIpAddress:
                aws:SourceIp:
                  - 173.245.48.0/20
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 141.101.64.0/18
                  - 108.162.192.0/18
                  - 190.93.240.0/20
                  - 188.114.96.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17
                  - 162.158.0.0/15
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 172.64.0.0/13
                  - 131.0.72.0/22
                  - 2400:cb00::/32
                  - 2606:4700::/32
                  - 2803:f800::/32
                  - 2405:b500::/32
                  - 2405:8100::/32
                  - 2a06:98c0::/29
                  - 2c0f:f248::/32

Outputs:
  RootBucketWebsiteURL:
    Description: The website URL for the root domain S3 bucket (0dev.io)
    Value: !GetAtt RootDomainBucket.WebsiteURL

  WwwBucketWebsiteURL:
    Description: The website URL for the www subdomain S3 bucket (www.0dev.io)
    Value: !GetAtt WwwDomainBucket.WebsiteURL

# added manually to 0dev.io bucket
# {
#     "Sid": "PublicReadGetObjectAllow",
#     "Effect": "Allow",
#     "Principal": "*",
#     "Action": "s3:GetObject",
#     "Resource": "arn:aws:s3:::0dev.io/*"
# }